### ISSUE TITLE
Problem with your TWRP

### ISSUE THREAD

**Issue by tmvkrpxl0** [amitkhairnar44/android_device_samsung_a6plte#1]
I intalled you twrp via odin, but there are those error
Invalid argument
Permission denied
so i tried wipe, but format data and change file system wasn't worked
My device: A605K (galaxy jean)
Mods: recovery & magisk boot img

**Comment by amitkhairnar44** [comment]
Yup there are some errors and that's due to issue with the kernel

**Comment by tmvkrpxl0** [comment]
so how can i fix this? just i have to wait? or do something with magisk?

**Comment by amitkhairnar44** [comment]
You have to wait until it's fixed.

**Comment by tmvkrpxl0** [comment]
So... when do you think it will be fixed?

**Comment by tmvkrpxl0** [comment]
Seeing this issue now makes me regret as my wording didn't have etiquette, Im sincerely sorry about that.
I don't quite remember how, but this issue has been fixed for me
